name: Rust Clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
